defaults: &defaults
  working_directory: /tmp

version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker build .
  test:
    machine: true
    steps:
      - checkout
      - run: docker build --tag tmp:1.0 .
      - run: docker run tmp:1.0
  integrate:
    machine: true
    steps:
      - checkout
      - run: .circleci/integrate.sh
  tag:
    machine: true
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/build
      - run: mkdir -p artifacts
      - run: cp /tmp/build/libgenerator.a artifacts
      - run: git add artifacts
      - run: git config --global user.email "circleci@stdio.work"
      - run: git config --global user.name "CircleCI Agent"
      - run: git commit -m "Artifacts"
      - run: git tag -a v0.5.$CIRCLE_BUILD_NUM -m "Auto-tagged v0.5."$CIRCLE_BUILD_NUM
      - run: git push origin --tags
workflows:
  version: 2
  integrate:
    jobs:
      - start_build:
          filters:
            branches:
              ignore:
                - master
          type: approval
      - build:
          requires:
            - start_build
      - test:
          requires:
            - build
      - start_integration:
          type: approval
          requires:
            - test
      - integrate:
          requires:
            - start_integration
          filters:
            branches:
              ignore:
                - master
